#!/bin/bash
#
# TBD: expand this into an expert script.
#
# You need to do a release on github first, and make some changes to setup.py.
# Follow,
# https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56
#
# Then,
#   python3 setup.py sdist
#   twine upload dist/*
#
